#!/usr/bin/env python3
"""Regenerate docs/SEED-RECIPES.md from seed/*.json for the human review gate (task 028).

Reads only; never edits the catalog. Run: python3 scripts/gen-seed-doc.py
"""
import json
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ingredients = json.loads((ROOT / "seed/ingredients.json").read_text())["ingredients"]
recipes = json.loads((ROOT / "seed/recipes.json").read_text())["recipes"]
by_name = {i["name"]: i for i in ingredients}


def flags(row):
    marks = [k[8].lower() for k in ("containsEgg", "containsDairy", "containsNuts", "containsGluten") if row[k]]
    return "".join(marks) or "—"


def minutes(r):
    return r["prepMinutes"] + r["cookMinutes"]


lines = []
lines.append("# Seed catalog review (task 028 — HUMAN gate)\n")
lines.append(
    "Generated by `python3 scripts/gen-seed-doc.py` from `seed/ingredients.json` and "
    "`seed/recipes.json`. Nothing here is editorialised: it is the catalog as the app will load "
    "it. Reply **approved: task 028** once you are happy with it, or list what to change and the "
    "build will fix the JSON.\n"
)
lines.append(f"- **{len(recipes)} recipes**, all vegetarian; **{len(ingredients)} ingredients**.")
meals = Counter(m for r in recipes for m in r["mealTypes"])
lines.append(
    "- Meals: "
    + ", ".join(f"{meals[m]} {m}" for m in ("breakfast", "lunch", "dinner", "snack"))
    + f". Quick (≤15 min): {sum(1 for r in recipes if minutes(r) <= 15)}."
)
apps = Counter(a for r in recipes for a in r["appliances"])
lines.append("- Appliances: " + ", ".join(f"{v} {k}" for k, v in apps.most_common()) + ".")
cuisines = Counter(r["cuisine"] for r in recipes)
lines.append("- Cuisines: " + ", ".join(f"{v} {k}" for k, v in cuisines.most_common()) + ".")
lines.append(f"- Lunchbox-friendly: {sum(1 for r in recipes if r['lunchboxOK'])}.")
lines.append("\nFlag key: **e** egg · **d** dairy · **n** nuts · **g** gluten.\n")

for meal in ("breakfast", "lunch", "dinner", "snack"):
    subset = [r for r in recipes if meal in r["mealTypes"]]
    lines.append(f"\n## {meal.capitalize()} ({len(subset)})\n")
    lines.append("| Recipe | Cuisine | Appliances | Min | Age | Flags | Kid | Make it kid-friendly |")
    lines.append("|---|---|---|---:|---:|---|---:|---|")
    for r in sorted(subset, key=lambda r: r["title"]):
        lines.append(
            "| {title} | {cuisine} | {apps} | {mins} | {age}+ | {flags} | {kid}/5 | {note} |".format(
                title=r["title"],
                cuisine=r["cuisine"],
                apps=", ".join(r["appliances"]),
                mins=minutes(r),
                age=r["minAgeYears"],
                flags=flags(r),
                kid=r["kidBaseline"],
                note=r["kidFriendlyNote"],
            )
        )

lines.append("\n## Ingredient catalog\n")
lines.append("| Category | Count | Examples |")
lines.append("|---|---:|---|")
cats = Counter(i["category"] for i in ingredients)
for cat, count in sorted(cats.items(), key=lambda kv: (-kv[1], kv[0])):
    examples = [i["name"] for i in ingredients if i["category"] == cat][:6]
    lines.append(f"| {cat} | {count} | {', '.join(examples)} |")

staples = [i["name"] for i in ingredients if i["isStaple"]]
snacks = [i["name"] for i in ingredients if i["isQuickHealthySnack"]]
lines.append(f"\n**Weekly staples ({len(staples)})** — bought every week whether or not a recipe needs them: "
             + ", ".join(sorted(staples)) + ".")
lines.append(f"\n**Quick healthy snacks ({len(snacks)})** — offered on the Today screen: "
             + ", ".join(sorted(snacks)) + ".")

lines.append("\n## Points to check\n")
checks = []
egg_recipes = [r for r in recipes if r["containsEgg"]]
checks.append(f"**Egg recipes ({len(egg_recipes)})**, hidden unless *Eggs OK* is on: "
              + ", ".join(r["title"] for r in egg_recipes) + ".")
nut_recipes = [r["title"] for r in recipes if r["containsNuts"]]
checks.append(f"**Recipes with nuts ({len(nut_recipes)})**, hidden when *Nut free* is on: "
              + ", ".join(sorted(nut_recipes)) + ".")
honey = [r["title"] for r in recipes if any(l["ingredientName"] == "Honey" for l in r["ingredients"])]
if honey:
    checks.append("**Contains honey** (never for under-1s; the youngest in this household is 4): "
                  + ", ".join(sorted(honey)) + ".")
age3 = [f"{r['title']} ({r['minAgeYears']}+)" for r in recipes if r["minAgeYears"] >= 3]
if age3:
    checks.append("**Age-gated at 3+** — these disappear from lunch and dinner while a "
                  "younger child is at the table: " + ", ".join(sorted(age3)) + ".")
long_ones = [f"{r['title']} ({minutes(r)} min)" for r in recipes if minutes(r) > 45 and "dinner" in r["mealTypes"]]
if long_ones:
    checks.append("**Over 45 minutes** — weekend dinners only, past the 35-minute weekday cap: "
                  + ", ".join(sorted(long_ones)) + ".")
optional_allergens = []
for r in recipes:
    optional = [l["ingredientName"] for l in r["ingredients"] if l["isOptional"]
                and any(by_name.get(l["ingredientName"], {}).get(k) for k in
                        ("containsEgg", "containsDairy", "containsNuts", "containsGluten"))]
    if optional:
        optional_allergens.append(f"{r['title']} ({', '.join(optional)})")
if optional_allergens:
    checks.append("**Allergen only in an optional ingredient** — the recipe is *not* flagged, "
                  "because it can be made without it: " + "; ".join(sorted(optional_allergens)) + ".")
checks.append("**Build change**: `dn-pasta-hidden-veg` listed *Red chili powder* with quantity 0; "
              "set to 1 g (optional, to taste).")
for check in checks:
    lines.append(f"- {check}")

lines.append("\n---\n")
lines.append("Nothing in this catalog mentions calories, weight or restriction (R2), and no recipe "
             "or note frames a food as good or bad for a child (R3).")

(ROOT / "docs/SEED-RECIPES.md").write_text("\n".join(lines) + "\n")
print(f"docs/SEED-RECIPES.md: {len(recipes)} recipes, {len(ingredients)} ingredients")
