#!/usr/bin/env python3
"""Regenerate a copy-review document from Rasoi/Copy/AppCopy.swift.

    python3 scripts/gen-copy-doc.py feedback   -> docs/COPY-FEEDBACK.md   (task 043)
    python3 scripts/gen-copy-doc.py nutrition  -> docs/COPY-NUTRITION.md  (task 058)

Reads only. Every user-facing string for settings, about, feedback and nutrition lives in
AppCopy.swift, so this lists exactly what a human has to approve.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "Rasoi/Copy/AppCopy.swift"

# Which MARK sections go in which review document, and what each screen must satisfy.
DOCS = {
    "feedback": {
        "path": "docs/COPY-FEEDBACK.md",
        "title": "Feedback, settings and about copy (task 043 — HUMAN gate)",
        "sections": ["About", "Feedback (shown after a meal is cooked)", "Data"],
    },
    "nutrition": {
        "path": "docs/COPY-NUTRITION.md",
        "title": "Nutrition and insights copy (task 058 — HUMAN gate)",
        "sections": ["Nutrition and insights"],
    },
}

SCREENS = {
    "About": "More › About, and the diet settings footer",
    "Feedback (shown after a meal is cooked)": "Today › Cook › How did it go?",
    "Data": "More › Your data (export, delete all data)",
    "Nutrition and insights": "Plan › week summary, Today, More › Insights",
}

RULES = {
    "About": "R2 — no calories, weight, BMI or restriction language. R1 — the privacy note must "
             "stay true: the only network call in the app is MapKit store search.",
    "Feedback (shown after a meal is cooked)": "R3 — never shames a child or a cook. A refused meal "
                                               "is “not today”. No scores, streaks or badges, and "
                                               "nothing here is shown to the children.",
    "Data": "R6 — deleting is explicit, double-confirmed and honestly described; the copy must not "
            "promise a backup that does not exist.",
    "Nutrition and insights": "R2 — food groups only, never quantities per person, calories, weight "
                              "or diet advice. R3 — a child is never described as a problem.",
}


def parse(source: str):
    """Yields (section, name, value) in file order."""
    section = "Other"
    lines = source.splitlines()
    index = 0
    while index < len(lines):
        line = lines[index]
        mark = re.match(r"\s*// MARK: - (.+)", line)
        if mark:
            section = mark.group(1).strip()
            index += 1
            continue
        multi = re.match(r'\s*static let (\w+) = """', line)
        if multi:
            body = []
            index += 1
            while index < len(lines) and '"""' not in lines[index]:
                body.append(lines[index].strip())
                index += 1
            # A trailing backslash in a Swift multi-line string joins the lines.
            text = " ".join(part[:-1].strip() if part.endswith("\\") else part for part in body)
            yield section, multi.group(1), re.sub(r"\s+", " ", text).strip()
            index += 1
            continue
        single = re.match(r'\s*static let (\w+) = "(.*)"$', line)
        if single:
            yield section, single.group(1), single.group(2)
            index += 1
            continue
        # Copy assembled from data, e.g. `static func lightOnHint(_ group: String) -> String`.
        built = re.match(r"\s*static func (\w+)\(.*\) -> String \{", line)
        if built and index + 1 < len(lines):
            body = lines[index + 1].strip()
            quoted = re.match(r'"(.*)"$', body)
            if quoted:
                yield section, f"{built.group(1)}()", quoted.group(1)
                index += 2
                continue
        index += 1


def main() -> None:
    which = sys.argv[1] if len(sys.argv) > 1 else "feedback"
    if which not in DOCS:
        raise SystemExit(f"unknown document '{which}'; choose from {', '.join(DOCS)}")
    spec = DOCS[which]
    entries = list(parse(SOURCE.read_text()))
    wanted = [e for e in entries if e[0] in spec["sections"]]
    if not wanted:
        raise SystemExit(f"no copy found for sections {spec['sections']} in {SOURCE}")

    out = [f"# {spec['title']}\n"]
    out.append(
        f"Generated by `python3 scripts/gen-copy-doc.py {which}` from `Rasoi/Copy/AppCopy.swift`, "
        "which holds every user-facing sentence in these screens. Reply **approved: task "
        f"{'043' if which == 'feedback' else '058'}** to accept, or say what to change.\n"
    )
    for section in spec["sections"]:
        rows = [e for e in wanted if e[0] == section]
        if not rows:
            continue
        out.append(f"\n## {section}\n")
        out.append(f"*Where it appears:* {SCREENS.get(section, '—')}  ")
        out.append(f"*Must satisfy:* {RULES.get(section, '—')}\n")
        for _, name, value in rows:
            out.append(f"**`{name}`**\n")
            out.append(f"> {value}\n")

    out.append("\n## What the build checked itself\n")
    banned = ["calorie", "calories", "bmi", "weight", "diet plan", "lose", "gain",
              "fat ", "skinny", "obese", "failed", "refused", "bad eater", "picky"]
    hits = [
        f"`{name}` contains “{word}”"
        for _, name, value in entries
        for word in banned
        if word in value.lower()
    ]
    if hits:
        out.append("Words that need a second look:\n")
        out.extend(f"- {hit}" for hit in hits)
    else:
        out.append(
            "- No copy in this file mentions calories, weight, BMI or dieting (R2).\n"
            "- No copy calls a meal or a child a failure (R3)."
        )

    if which == "nutrition":
        out.append("\n## The MyPlate table behind the dots\n")
        out.append(
            "Daily amounts from the USDA's MyPlate guidance, held in "
            "`NutritionCoverage.targets(for:)`. **v1 never renders these numbers.** The engine "
            "uses food groups only, and the UI shows one dot per group per day.\n"
        )
        out.append("| Age band | Fruit (cups) | Vegetables (cups) | Grains (oz-eq) | Protein (oz-eq) | Dairy (cups) |")
        out.append("|---|---|---|---|---|---|")
        out.append("| Preschool (2–5) | 1–1.5 | 1–1.5 | 3–5 | 2–4 | 2–2.5 |")
        out.append("| Child (6–8) | 1–1.5 | 1.5–2 | 5–6 | 4–5 | 2.5 |")
        out.append("| Preteen (9–13) | 1.5–2 | 2–2.5 | 5–6 | 5–5.5 | 3 |")
        out.append("| Teen (14–18) | 1.5–2 | 2.5–3 | 6–8 | 5–6.5 | 3 |")
        out.append("| Adult | 1.5–2 | 2.5–3 | 6–8 | 5–6.5 | 3 |")
        out.append("\nSource: <https://www.myplate.gov/life-stages/kids> and "
                   "<https://www.myplate.gov/eat-healthy/what-is-myplate> (USDA, MyPlate Plan by "
                   "age). Rasoi is a planning tool, not nutrition advice.")

    (ROOT / spec["path"]).write_text("\n".join(out) + "\n")
    print(f"{spec['path']}: {len(wanted)} strings")


if __name__ == "__main__":
    main()
