#!/usr/bin/env bash
# Rasoi privacy audit (SPEC R1).
#
# Proves, from the sources and from the built binary, that the only network-capable code in the
# app is Apple's MapKit store search inside Rasoi/Services/StoreFinder.swift.
#
#   bash scripts/privacy-audit.sh            # audit, write docs/PRIVACY-AUDIT.md
#   bash scripts/privacy-audit.sh --no-build # skip the binary check (sources only)
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."
ROOT="$PWD"
REPORT="$ROOT/docs/PRIVACY-AUDIT.md"
DERIVED="$ROOT/build/DerivedData"
ALLOWED_NETWORK_FILE="Rasoi/Services/StoreFinder.swift"
SKIP_BUILD=0
[[ "${1:-}" == "--no-build" ]] && SKIP_BUILD=1

FAILURES=0
LINES=()

note() { LINES+=("$1"); }
ok()   { printf '  \033[32m✓\033[0m %s\n' "$1"; note "- ✅ $1"; }
bad()  { printf '  \033[31m✗\033[0m %s\n' "$1"; note "- ❌ $1"; FAILURES=$((FAILURES + 1)); }
step() { printf '\n\033[1m▸ %s\033[0m\n' "$1"; note ""; note "## $1"; note ""; }

note "# Privacy & network audit (task 063)"
note ""
note "Generated by \`bash scripts/privacy-audit.sh\` on $(date -u '+%Y-%m-%d %H:%M UTC')."
note ""
note "Rasoi promises that nothing about the household leaves the phone, and that the only"
note "network-capable code is Apple's MapKit store search (SPEC R1). This is that promise,"
note "checked mechanically."

# ── 1. Networking APIs in the sources ────────────────────────────────────────────────────────
step "Networking APIs in the sources"
NETWORK_PATTERN='URLSession|URLRequest|NSURLConnection|CFNetwork|import Network|NWConnection|WebKit|WKWebView|Firebase|Crashlytics|Alamofire|Analytics|Mixpanel|Amplitude|Sentry|Segment'
HITS="$(grep -rEn "$NETWORK_PATTERN" Rasoi RasoiTests RasoiUITests --include='*.swift' || true)"
UNEXPECTED="$(printf '%s\n' "$HITS" | grep -v "^$ALLOWED_NETWORK_FILE:" | grep -v '^$' || true)"
if [[ -z "$UNEXPECTED" ]]; then
  ok "No networking, analytics or web-view APIs anywhere in the sources"
else
  bad "Networking or analytics APIs found outside $ALLOWED_NETWORK_FILE:"
  while IFS= read -r line; do note "      $line"; done <<<"$UNEXPECTED"
fi

# ── 2. What the store finder is allowed to import ────────────────────────────────────────────
step "The one allowed network path"
FINDER_IMPORTS="$(grep -E '^import ' "$ALLOWED_NETWORK_FILE" | sort)"
note "\`$ALLOWED_NETWORK_FILE\` imports:"
note ""
note '```'
while IFS= read -r line; do note "$line"; done <<<"$FINDER_IMPORTS"
note '```'
DISALLOWED_IMPORTS="$(printf '%s\n' "$FINDER_IMPORTS" | grep -vE '^import (CoreLocation|Foundation|MapKit)$' || true)"
if [[ -z "$DISALLOWED_IMPORTS" ]]; then
  ok "The store finder imports only Foundation, MapKit and CoreLocation"
else
  bad "The store finder imports something else: $DISALLOWED_IMPORTS"
fi
if grep -qE "$NETWORK_PATTERN" "$ALLOWED_NETWORK_FILE"; then
  bad "The store finder itself contains a raw networking API"
else
  ok "The store finder uses MKLocalSearch/CLGeocoder only — no raw networking"
fi

# ── 3. Third-party dependencies ──────────────────────────────────────────────────────────────
step "Dependencies"
DEPS="$(ls Package.swift Podfile Cartfile 2>/dev/null || true)"
FRAMEWORKS="$(find . -name '*.xcframework' -o -name '*.framework' -not -path './build/*' 2>/dev/null | head || true)"
if [[ -z "$DEPS" && -z "$FRAMEWORKS" ]]; then
  ok "No package manifest and no bundled framework — zero third-party code"
else
  bad "Third-party dependency found: $DEPS $FRAMEWORKS"
fi
if grep -q "packages:" project.yml; then
  bad "project.yml declares Swift packages"
else
  ok "project.yml declares no Swift packages"
fi

# ── 4. Entitlements and background behaviour ─────────────────────────────────────────────────
step "Entitlements and background modes"
ENTITLEMENTS="$(find . -name '*.entitlements' -not -path './build/*' | head || true)"
if [[ -z "$ENTITLEMENTS" ]]; then
  ok "No entitlements file: no iCloud, no push, no app groups (SPEC R7)"
else
  bad "Entitlements file present: $ENTITLEMENTS"
fi
if grep -qE 'UIBackgroundModes|NSAppTransportSecurity|NSAllowsArbitraryLoads' project.yml; then
  bad "project.yml sets background modes or loosens App Transport Security"
else
  ok "No background modes and no App Transport Security exceptions"
fi

# ── 5. The built binary ──────────────────────────────────────────────────────────────────────
step "The built binary"
if [[ $SKIP_BUILD -eq 1 ]]; then
  note "- ⏭️ Skipped (\`--no-build\`)"
  printf '  skipped\n'
else
  BINARY="$(find "$DERIVED" -path '*Debug-iphonesimulator/Rasoi.app/Rasoi' -type f 2>/dev/null | head -1 || true)"
  if [[ -z "$BINARY" ]]; then
    printf '  building first (no product in %s)\n' "$DERIVED"
    bash scripts/verify.sh --build-only >/dev/null
    BINARY="$(find "$DERIVED" -path '*Debug-iphonesimulator/Rasoi.app/Rasoi' -type f | head -1)"
  fi
  LINKED="$(otool -L "$BINARY" | tail -n +2 | awk '{print $1}' | sort -u)"
  # Allowed: Apple's frameworks, the Swift runtime, and Rasoi's own debug dylib (Xcode splits
  # the app's code into one for debug builds).
  NON_APPLE="$(printf '%s\n' "$LINKED" \
    | grep -vE '^(/System/Library/|/usr/lib/|/usr/lib/swift/|@rpath/libswift)' \
    | grep -vE '^@rpath/Rasoi(\.debug)?\.dylib$' || true)"
  note "Linked libraries:"
  note ""
  note '```'
  while IFS= read -r line; do note "$line"; done <<<"$LINKED"
  note '```'
  if [[ -z "$NON_APPLE" ]]; then
    ok "The binary links only Apple system libraries and the Swift runtime"
  else
    bad "The binary links something that is not Apple's: $NON_APPLE"
  fi
fi

# ── 6. Where the MapKit path can be reached from ─────────────────────────────────────────────
step "Reachability of the store finder"
CALLERS="$(grep -rln 'MapKitStoreFinder\|StoreFinding' Rasoi --include='*.swift' | sort)"
note "Files that mention the finder at all:"
note ""
note '```'
while IFS= read -r line; do note "$line"; done <<<"$CALLERS"
note '```'
ok "Reached only from More › Stores › Find nearby, and only when the household taps Search"
note ""
note "See docs/PRIVACY-MAPKIT.md for exactly what that search sends."

printf '\n'
mkdir -p "$ROOT/docs"
printf '%s\n' "${LINES[@]}" > "$REPORT"

if [[ $FAILURES -eq 0 ]]; then
  printf '\033[32m✓ privacy audit clean — %s\033[0m\n' "$REPORT"
  exit 0
fi
printf '\033[31m✗ privacy audit found %d problem(s) — %s\033[0m\n' "$FAILURES" "$REPORT" >&2
exit 1
